---
title: "Sesión 02"
date: "2022-10-05"
---

## Objetivos

En esta sesión se buscará abordar los siguientes temas: 

- Estrategias gráficas de inspección/exploración de datos con ggplot().

- Operador asignar y pipe (%>%). 

- Manejo de datos con dplyr 1, funciones select(), filter(), y arrange().

## Materiales

::: {.panel-tabset}

### Clase grabada

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/757625946?h=e75403206e&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 02 - Visualizaci&amp;oacute;n e introducci&amp;oacute;n al manejo de datos con R"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>


### Slides

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
```

```{r show-slide-tabs1, echo=FALSE, results="asis"}
slide_buttons("/slides/sesion02/sesion02_chalkboard-speaker")
```

```{=html}
<iframe width="780" height="500" src="../slides/sesion02/sesion02_chalkboard-speaker.html" title="Sesión 2 - Gráficos en ggplot2 y manejo de datos con dplyr"></iframe>
```

### Talleres

- Puede descargar los archivos generados en la carpeta `taller02` en el siguiente enlace: [Aquí](https://drive.google.com/drive/folders/18PHD4uNhXBJVKyLxfl6q9XoYx0ax9hXG?usp=sharing).


:::


