---
title: "Sesión 05"
date: "2022-10-12"
---

## Objetivos

En esta sesión se buscará abordar los siguientes temas: 

- Inspección inicial de datos 2 y análisis descriptivo con summarise(), count(), group_by(). 

- Creación automatizada de Tabla 1 reproducible con paquete gtsummary().


## Materiales

::: {.panel-tabset}

### Clase grabada

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/760611161?h=56caf67751&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 05 - Intro a an&amp;aacute;lisis descriptivo y tabla descriptiva reproducible"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>


### Slides

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
```

```{r show-slide-tabs1, echo=FALSE, results="asis"}
slide_buttons("/slides/sesion05/sesion05_chalkboard-speaker")
```

```{=html}
<iframe width="780" height="500" src="../slides/sesion05/sesion05_chalkboard-speaker.html" title="Sesión 5 - Analisis descriptivo y tabla automatizada"></iframe>
```

### Talleres

- Puede descargar los archivos generados en la carpeta `taller05` en el siguiente enlace: [Aquí](https://drive.google.com/drive/folders/1WzfYdr5Bd8wiDPUGhg1JDz_6eoQDstRz?usp=sharing).


:::


