---
title: "Sesión 11"
date: "2022-10-26"
---

## Objetivos

En esta sesión se buscará abordar los siguientes temas: 

- Ajuste

- Introducción a inferencia causal

- Confusión, mediador, colisionador

- Uso de DAG para seleccionar variables


## Materiales

::: {.panel-tabset}

### Clase grabada

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/765239627?h=60c1286056&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 11 - Ajuste e intro a inferencia causal: confusi&amp;oacute;n"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>


### Slides

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
```

```{r show-slide-tabs1, echo=FALSE, results="asis"}
slide_buttons("/slides/sesion11/sesion11_chalkboard-speaker")
```

```{=html}
<iframe width="780" height="500" src="../slides/sesion11/sesion11_chalkboard-speaker.html" title="Sesión 11 - Estrategias de modelado explicativo 2"></iframe>
```

### Talleres

- Puede descargar los archivos generados en la carpeta `taller11` en el siguiente enlace: [Aquí](https://drive.google.com/drive/folders/1qrelWtFg9R-WaPbNKgu0Kf59LXhiLI1f?usp=sharing).


:::


